export const ALL_AUTHORITY_REQUEST = 'ALL_AUTHORITY_REQUEST';
export const ALL_AUTHORITY_SUCCESS = 'ALL_AUTHORITY_SUCCESS';
export const ALL_AUTHORITY_FAIL = 'ALL_AUTHORITY_FAIL';

export const ADD_AUTHORITY_REQUEST = 'ADD_AUTHORITY_REQUEST';
export const ADD_AUTHORITY_SUCCESS = 'ADD_AUTHORITY_SUCCESS';
export const ADD_AUTHORITY_FAIL = 'ADD_AUTHORITY_FAIL';

export const DELETE_AUTHORITY_REQUEST = 'DELETE_AUTHORITY_REQUEST';
export const DELETE_AUTHORITY_SUCCESS = 'DELETE_AUTHORITY_SUCCESS';
export const DELETE_AUTHORITY_FAIL = 'DELETE_AUTHORITY_FAIL';

export const UPDATE_AUTHORITY_REQUEST = 'UPDATE_AUTHORITY_REQUEST';
export const UPDATE_AUTHORITY_SUCCESS = 'UPDATE_AUTHORITY_SUCCESS';
export const UPDATE_AUTHORITY_FAIL = 'UPDATE_AUTHORITY_FAIL';

export const SEARCH_AUTHORITY_REQUEST = 'SEARCH_AUTHORITY_REQUEST';
export const SEARCH_AUTHORITY_SUCCESS = 'SEARCH_AUTHORITY_SUCCESS';
export const SEARCH_AUTHORITY_FAIL = 'SEARCH_AUTHORITY_FAIL';
