export const ALL_BILL_DETAIL_REQUEST = 'ALL_BILL_DETAIL_REQUEST';
export const ALL_BILL_DETAIL_SUCCESS = 'ALL_BILL_DETAIL_SUCCESS';
export const ALL_BILL_DETAIL_FAIL = 'ALL_BILL_DETAIL_FAIL';

export const ADD_BILL_DETAIL_REQUEST = 'ADD_BILL_DETAIL_REQUEST';
export const ADD_BILL_DETAIL_SUCCESS = 'ADD_BILL_DETAIL_SUCCESS';
export const ADD_BILL_DETAIL_FAIL = 'ADD_BILL_DETAIL_FAIL';

export const DELETE_BILL_DETAIL_REQUEST = 'DELETE_BILL_DETAIL_REQUEST';
export const DELETE_BILL_DETAIL_SUCCESS = 'DELETE_BILL_DETAIL_SUCCESS';
export const DELETE_BILL_DETAIL_FAIL = 'DELETE_BILL_DETAIL_FAIL';

export const UPDATE_BILL_DETAIL_REQUEST = 'UPDATE_BILL_DETAIL_REQUEST';
export const UPDATE_BILL_DETAIL_SUCCESS = 'UPDATE_BILL_DETAIL_SUCCESS';
export const UPDATE_BILL_DETAIL_FAIL = 'UPDATE_BILL_DETAIL_FAIL';

export const SEARCH_BILL_DETAIL_REQUEST = 'SEARCH_BILL_DETAIL_REQUEST';
export const SEARCH_BILL_DETAIL_SUCCESS = 'SEARCH_BILL_DETAIL_SUCCESS';
export const SEARCH_BILL_DETAIL_FAIL = 'SEARCH_BILL_DETAIL_FAIL';
