export const ALL_BILL_REQUEST = 'ALL_BILL_REQUEST';
export const ALL_BILL_SUCCESS = 'ALL_BILL_SUCCESS';
export const ALL_BILL_FAIL = 'ALL_BILL_FAIL';

export const ADD_BILL_REQUEST = 'ADD_BILL_REQUEST';
export const ADD_BILL_SUCCESS = 'ADD_BILL_SUCCESS';
export const ADD_BILL_FAIL = 'ADD_BILL_FAIL';

export const DELETE_BILL_REQUEST = 'DELETE_BILL_REQUEST';
export const DELETE_BILL_SUCCESS = 'DELETE_BILL_SUCCESS';
export const DELETE_BILL_FAIL = 'DELETE_BILL_FAIL';

export const UPDATE_BILL_REQUEST = 'UPDATE_BILL_REQUEST';
export const UPDATE_BILL_SUCCESS = 'UPDATE_BILL_SUCCESS';
export const UPDATE_BILL_FAIL = 'UPDATE_BILL_FAIL';

export const SEARCH_BILL_REQUEST = 'SEARCH_BILL_REQUEST';
export const SEARCH_BILL_SUCCESS = 'SEARCH_BILL_SUCCESS';
export const SEARCH_BILL_FAIL = 'SEARCH_BILL_FAIL';
