export const ALL_CONTRACT_MEMBER_REQUEST = 'ALL_CONTRACT_MEMBER_REQUEST';
export const ALL_CONTRACT_MEMBER_SUCCESS = 'ALL_CONTRACT_MEMBER_SUCCESS';
export const ALL_CONTRACT_MEMBER_FAIL = 'ALL_CONTRACT_MEMBER_FAIL';

export const ADD_CONTRACT_MEMBER_REQUEST = 'ADD_CONTRACT_MEMBER_REQUEST';
export const ADD_CONTRACT_MEMBER_SUCCESS = 'ADD_CONTRACT_MEMBER_SUCCESS';
export const ADD_CONTRACT_MEMBER_FAIL = 'ADD_CONTRACT_MEMBER_FAIL';

export const DELETE_CONTRACT_MEMBER_REQUEST = 'DELETE_CONTRACT_MEMBER_REQUEST';
export const DELETE_CONTRACT_MEMBER_SUCCESS = 'DELETE_CONTRACT_MEMBER_SUCCESS';
export const DELETE_CONTRACT_MEMBER_FAIL = 'DELETE_CONTRACT_MEMBER_FAIL';

export const UPDATE_CONTRACT_MEMBER_REQUEST = 'UPDATE_CONTRACT_MEMBER_REQUEST';
export const UPDATE_CONTRACT_MEMBER_SUCCESS = 'UPDATE_CONTRACT_MEMBER_SUCCESS';
export const UPDATE_CONTRACT_MEMBER_FAIL = 'UPDATE_CONTRACT_MEMBER_FAIL';

export const SEARCH_CONTRACT_MEMBER_REQUEST = 'SEARCH_CONTRACT_MEMBER_REQUEST';
export const SEARCH_CONTRACT_MEMBER_SUCCESS = 'SEARCH_CONTRACT_MEMBER_SUCCESS';
export const SEARCH_CONTRACT_MEMBER_FAIL = 'SEARCH_CONTRACT_MEMBER_FAIL';
