export const ALL_CONTRACT_REQUEST = 'ALL_CONTRACT_REQUEST';
export const ALL_CONTRACT_SUCCESS = 'ALL_CONTRACT_SUCCESS';
export const ALL_CONTRACT_FAIL = 'ALL_CONTRACT_FAIL';

export const ADD_CONTRACT_REQUEST = 'ADD_CONTRACT_REQUEST';
export const ADD_CONTRACT_SUCCESS = 'ADD_CONTRACT_SUCCESS';
export const ADD_CONTRACT_FAIL = 'ADD_CONTRACT_FAIL';

export const DELETE_CONTRACT_REQUEST = 'DELETE_CONTRACT_REQUEST';
export const DELETE_CONTRACT_SUCCESS = 'DELETE_CONTRACT_SUCCESS';
export const DELETE_CONTRACT_FAIL = 'DELETE_CONTRACT_FAIL';

export const UPDATE_CONTRACT_REQUEST = 'UPDATE_CONTRACT_REQUEST';
export const UPDATE_CONTRACT_SUCCESS = 'UPDATE_CONTRACT_SUCCESS';
export const UPDATE_CONTRACT_FAIL = 'UPDATE_CONTRACT_FAIL';

export const SEARCH_CONTRACT_REQUEST = 'SEARCH_CONTRACT_REQUEST';
export const SEARCH_CONTRACT_SUCCESS = 'SEARCH_CONTRACT_SUCCESS';
export const SEARCH_CONTRACT_FAIL = 'SEARCH_CONTRACT_FAIL';
