export const ALL_ELECTRIC_WATER_REQUEST = 'ALL_ELECTRIC_WATER_REQUEST';
export const ALL_ELECTRIC_WATER_SUCCESS = 'ALL_ELECTRIC_WATER_SUCCESS';
export const ALL_ELECTRIC_WATER_FAIL = 'ALL_ELECTRIC_WATER_FAIL';

export const ADD_ELECTRIC_WATER_REQUEST = 'ADD_ELECTRIC_WATER_REQUEST';
export const ADD_ELECTRIC_WATER_SUCCESS = 'ADD_ELECTRIC_WATER_SUCCESS';
export const ADD_ELECTRIC_WATER_FAIL = 'ADD_ELECTRIC_WATER_FAIL';

export const DELETE_ELECTRIC_WATER_REQUEST = 'DELETE_ELECTRIC_WATER_REQUEST';
export const DELETE_ELECTRIC_WATER_SUCCESS = 'DELETE_ELECTRIC_WATER_SUCCESS';
export const DELETE_ELECTRIC_WATER_FAIL = 'DELETE_ELECTRIC_WATER_FAIL';

export const UPDATE_ELECTRIC_WATER_REQUEST = 'UPDATE_ELECTRIC_WATER_REQUEST';
export const UPDATE_ELECTRIC_WATER_SUCCESS = 'UPDATE_ELECTRIC_WATER_SUCCESS';
export const UPDATE_ELECTRIC_WATER_FAIL = 'UPDATE_ELECTRIC_WATER_FAIL';

export const SEARCH_ELECTRIC_WATER_REQUEST = 'SEARCH_ELECTRIC_WATER_REQUEST';
export const SEARCH_ELECTRIC_WATER_SUCCESS = 'SEARCH_ELECTRIC_WATER_SUCCESS';
export const SEARCH_ELECTRIC_WATER_FAIL = 'SEARCH_ELECTRIC_WATER_FAIL';
