export const ADD_IMAGE_REQUEST = 'ADD_IMAGE_REQUEST';
export const ADD_IMAGE_SUCCESS = 'ADD_IMAGE_SUCCESS';
export const ADD_IMAGE_FAIL = 'ADD_IMAGE_FAIL';

export const ADD_LIST_IMAGE_REQUEST = 'ADD_LIST_IMAGE_REQUEST';
export const ADD_LIST_IMAGE_SUCCESS = 'ADD_LIST_IMAGE_SUCCESS';
export const ADD_LIST_IMAGE_FAIL = 'ADD_LIST_IMAGE_FAIL';
