export const ALL_PAYMENT_REQUEST = 'ALL_PAYMENT_REQUEST';
export const ALL_PAYMENT_SUCCESS = 'ALL_PAYMENT_SUCCESS';
export const ALL_PAYMENT_FAIL = 'ALL_PAYMENT_FAIL';

export const ADD_PAYMENT_REQUEST = 'ADD_PAYMENT_REQUEST';
export const ADD_PAYMENT_SUCCESS = 'ADD_PAYMENT_SUCCESS';
export const ADD_PAYMENT_FAIL = 'ADD_PAYMENT_FAIL';

export const DELETE_PAYMENT_REQUEST = 'DELETE_PAYMENT_REQUEST';
export const DELETE_PAYMENT_SUCCESS = 'DELETE_PAYMENT_SUCCESS';
export const DELETE_PAYMENT_FAIL = 'DELETE_PAYMENT_FAIL';

export const UPDATE_PAYMENT_REQUEST = 'UPDATE_PAYMENT_REQUEST';
export const UPDATE_PAYMENT_SUCCESS = 'UPDATE_PAYMENT_SUCCESS';
export const UPDATE_PAYMENT_FAIL = 'UPDATE_PAYMENT_FAIL';

export const SEARCH_PAYMENT_REQUEST = 'SEARCH_PAYMENT_REQUEST';
export const SEARCH_PAYMENT_SUCCESS = 'SEARCH_PAYMENT_SUCCESS';
export const SEARCH_PAYMENT_FAIL = 'SEARCH_PAYMENT_FAIL';
