export const ALL_RENTER_REQUEST = 'ALL_RENTER_REQUEST';
export const ALL_RENTER_SUCCESS = 'ALL_RENTER_SUCCESS';
export const ALL_RENTER_FAIL = 'ALL_RENTER_FAIL';

export const ADD_RENTER_REQUEST = 'ADD_RENTER_REQUEST';
export const ADD_RENTER_SUCCESS = 'ADD_RENTER_SUCCESS';
export const ADD_RENTER_FAIL = 'ADD_RENTER_FAIL';

export const DELETE_RENTER_REQUEST = 'DELETE_RENTER_REQUEST';
export const DELETE_RENTER_SUCCESS = 'DELETE_RENTER_SUCCESS';
export const DELETE_RENTER_FAIL = 'DELETE_RENTER_FAIL';

export const UPDATE_RENTER_REQUEST = 'UPDATE_RENTER_REQUEST';
export const UPDATE_RENTER_SUCCESS = 'UPDATE_RENTER_SUCCESS';
export const UPDATE_RENTER_FAIL = 'UPDATE_RENTER_FAIL';

export const SEARCH_RENTER_REQUEST = 'SEARCH_RENTER_REQUEST';
export const SEARCH_RENTER_SUCCESS = 'SEARCH_RENTER_SUCCESS';
export const SEARCH_RENTER_FAIL = 'SEARCH_RENTER_FAIL';
