export const ALL_ROLE_REQUEST = 'ALL_ROLE_REQUEST';
export const ALL_ROLE_SUCCESS = 'ALL_ROLE_SUCCESS';
export const ALL_ROLE_FAIL = 'ALL_ROLE_FAIL';

export const ADD_ROLE_REQUEST = 'ADD_ROLE_REQUEST';
export const ADD_ROLE_SUCCESS = 'ADD_ROLE_SUCCESS';
export const ADD_ROLE_FAIL = 'ADD_ROLE_FAIL';

export const DELETE_ROLE_REQUEST = 'DELETE_ROLE_REQUEST';
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';
export const DELETE_ROLE_FAIL = 'DELETE_ROLE_FAIL';

export const UPDATE_ROLE_REQUEST = 'UPDATE_ROLE_REQUEST';
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS';
export const UPDATE_ROLE_FAIL = 'UPDATE_ROLE_FAIL';

export const SEARCH_ROLE_REQUEST = 'SEARCH_ROLE_REQUEST';
export const SEARCH_ROLE_SUCCESS = 'SEARCH_ROLE_SUCCESS';
export const SEARCH_ROLE_FAIL = 'SEARCH_ROLE_FAIL';
