export const ALL_ROOM_SERVICE_REQUEST = 'ALL_ROOM_SERVICE_REQUEST';
export const ALL_ROOM_SERVICE_SUCCESS = 'ALL_ROOM_SERVICE_SUCCESS';
export const ALL_ROOM_SERVICE_FAIL = 'ALL_ROOM_SERVICE_FAIL';

export const ADD_ROOM_SERVICE_REQUEST = 'ADD_ROOM_SERVICE_REQUEST';
export const ADD_ROOM_SERVICE_SUCCESS = 'ADD_ROOM_SERVICE_SUCCESS';
export const ADD_ROOM_SERVICE_FAIL = 'ADD_ROOM_SERVICE_FAIL';

export const DELETE_ROOM_SERVICE_REQUEST = 'DELETE_ROOM_SERVICE_REQUEST';
export const DELETE_ROOM_SERVICE_SUCCESS = 'DELETE_ROOM_SERVICE_SUCCESS';
export const DELETE_ROOM_SERVICE_FAIL = 'DELETE_ROOM_SERVICE_FAIL';

export const UPDATE_ROOM_SERVICE_REQUEST = 'UPDATE_ROOM_SERVICE_REQUEST';
export const UPDATE_ROOM_SERVICE_SUCCESS = 'UPDATE_ROOM_SERVICE_SUCCESS';
export const UPDATE_ROOM_SERVICE_FAIL = 'UPDATE_ROOM_SERVICE_FAIL';

export const SEARCH_ROOM_SERVICE_REQUEST = 'SEARCH_ROOM_SERVICE_REQUEST';
export const SEARCH_ROOM_SERVICE_SUCCESS = 'SEARCH_ROOM_SERVICE_SUCCESS';
export const SEARCH_ROOM_SERVICE_FAIL = 'SEARCH_ROOM_SERVICE_FAIL';
