export const ALL_ROOM_REQUEST = 'ALL_ROOM_REQUEST';
export const ALL_ROOM_SUCCESS = 'ALL_ROOM_SUCCESS';
export const ALL_ROOM_FAIL = 'ALL_ROOM_FAIL';

export const ADD_ROOM_REQUEST = 'ADD_ROOM_REQUEST';
export const ADD_ROOM_SUCCESS = 'ADD_ROOM_SUCCESS';
export const ADD_ROOM_FAIL = 'ADD_ROOM_FAIL';

export const DELETE_ROOM_REQUEST = 'DELETE_ROOM_REQUEST';
export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS';
export const DELETE_ROOM_FAIL = 'DELETE_ROOM_FAIL';

export const UPDATE_ROOM_REQUEST = 'UPDATE_ROOM_REQUEST';
export const UPDATE_ROOM_SUCCESS = 'UPDATE_ROOM_SUCCESS';
export const UPDATE_ROOM_FAIL = 'UPDATE_ROOM_FAIL';

export const SEARCH_ROOM_REQUEST = 'SEARCH_ROOM_REQUEST';
export const SEARCH_ROOM_SUCCESS = 'SEARCH_ROOM_SUCCESS';
export const SEARCH_ROOM_FAIL = 'SEARCH_ROOM_FAIL';
