export const ALL_ROOM_TYPE_REQUEST = 'ALL_ROOM_TYPE_REQUEST';
export const ALL_ROOM_TYPE_SUCCESS = 'ALL_ROOM_TYPE_SUCCESS';
export const ALL_ROOM_TYPE_FAIL = 'ALL_ROOM_TYPE_FAIL';

export const ADD_ROOM_TYPE_REQUEST = 'ADD_ROOM_TYPE_REQUEST';
export const ADD_ROOM_TYPE_SUCCESS = 'ADD_ROOM_TYPE_SUCCESS';
export const ADD_ROOM_TYPE_FAIL = 'ADD_ROOM_TYPE_FAIL';

export const DELETE_ROOM_TYPE_REQUEST = 'DELETE_ROOM_TYPE_REQUEST';
export const DELETE_ROOM_TYPE_SUCCESS = 'DELETE_ROOM_TYPE_SUCCESS';
export const DELETE_ROOM_TYPE_FAIL = 'DELETE_ROOM_TYPE_FAIL';

export const UPDATE_ROOM_TYPE_REQUEST = 'UPDATE_ROOM_TYPE_REQUEST';
export const UPDATE_ROOM_TYPE_SUCCESS = 'UPDATE_ROOM_TYPE_SUCCESS';
export const UPDATE_ROOM_TYPE_FAIL = 'UPDATE_ROOM_TYPE_FAIL';

export const SEARCH_ROOM_TYPE_REQUEST = 'SEARCH_ROOM_TYPE_REQUEST';
export const SEARCH_ROOM_TYPE_SUCCESS = 'SEARCH_ROOM_TYPE_SUCCESS';
export const SEARCH_ROOM_TYPE_FAIL = 'SEARCH_ROOM_TYPE_FAIL';
