export const ALL_SERVICE_REQUEST = 'ALL_SERVICE_REQUEST';
export const ALL_SERVICE_SUCCESS = 'ALL_SERVICE_SUCCESS';
export const ALL_SERVICE_FAIL = 'ALL_SERVICE_FAIL';

export const ADD_SERVICE_REQUEST = 'ADD_SERVICE_REQUEST';
export const ADD_SERVICE_SUCCESS = 'ADD_SERVICE_SUCCESS';
export const ADD_SERVICE_FAIL = 'ADD_SERVICE_FAIL';

export const DELETE_SERVICE_REQUEST = 'DELETE_SERVICE_REQUEST';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';
export const DELETE_SERVICE_FAIL = 'DELETE_SERVICE_FAIL';

export const UPDATE_SERVICE_REQUEST = 'UPDATE_SERVICE_REQUEST';
export const UPDATE_SERVICE_SUCCESS = 'UPDATE_SERVICE_SUCCESS';
export const UPDATE_SERVICE_FAIL = 'UPDATE_SERVICE_FAIL';

export const SEARCH_SERVICE_REQUEST = 'SEARCH_SERVICE_REQUEST';
export const SEARCH_SERVICE_SUCCESS = 'SEARCH_SERVICE_SUCCESS';
export const SEARCH_SERVICE_FAIL = 'SEARCH_SERVICE_FAIL';
