export const ALL_STAFF_REQUEST = 'ALL_STAFF_REQUEST';
export const ALL_STAFF_SUCCESS = 'ALL_STAFF_SUCCESS';
export const ALL_STAFF_FAIL = 'ALL_STAFF_FAIL';

export const ADD_STAFF_REQUEST = 'ADD_STAFF_REQUEST';
export const ADD_STAFF_SUCCESS = 'ADD_STAFF_SUCCESS';
export const ADD_STAFF_FAIL = 'ADD_STAFF_FAIL';

export const DELETE_STAFF_REQUEST = 'DELETE_STAFF_REQUEST';
export const DELETE_STAFF_SUCCESS = 'DELETE_STAFF_SUCCESS';
export const DELETE_STAFF_FAIL = 'DELETE_STAFF_FAIL';

export const UPDATE_STAFF_REQUEST = 'UPDATE_STAFF_REQUEST';
export const UPDATE_STAFF_SUCCESS = 'UPDATE_STAFF_SUCCESS';
export const UPDATE_STAFF_FAIL = 'UPDATE_STAFF_FAIL';

export const SEARCH_STAFF_REQUEST = 'SEARCH_STAFF_REQUEST';
export const SEARCH_STAFF_SUCCESS = 'SEARCH_STAFF_SUCCESS';
export const SEARCH_STAFF_FAIL = 'SEARCH_STAFF_FAIL';
